version: '3.9'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${SPRING_DATABASE_USERNAME}
      POSTGRES_USER: ${SPRING_DATABASE_USERNAME}
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATABASE_NAME: ${SPRING_DATABASE_NAME}
      SPRING_DATABASE_HOST: ${SPRING_DATABASE_HOST}
      SPRING_DATABASE_USERNAME: ${SPRING_DATABASE_USERNAME}
      SPRING_DATABASE_PASSWORD: ${SPRING_DATABASE_PASSWORD}